### PR TITLE
install curl if not installed

### LINKED ISSUE #51: Line 4 and Line 21 curl command not found
Hey Guys,
i'm trying to install the vitasdk but cannot succeed.
i made the steps from the installation tutorial on linux (ubuntu) but everytime when i want to install the toolchain it ends up with the curl command not found line 4 at ./bootstrap-vitasdk.sh and at ./install-all.sh it is the line 21
Followed this Guide:
https://vitasdk.org/

i made some screenshots for you Guys... can you guide me to success and tell me what i'm doing wrong?
Bildschirmfoto vom 2020-01-18 20-34-12
Bildschirmfoto vom 2020-01-18 20-36-13
Bildschirmfoto vom 2020-01-18 20-37-16

EDIT:
tried with sudo -E but the same error
Bildschirmfoto vom 2020-01-18 20-50-39

### PR DESCRIPTION
**Pull request by yne**
Shall fix https://github.com/vitasdk/vdpm/issues/51

### CODE REVIEW

File: include/install-vitasdk.sh [hunk 1]
```diff
@@ -10,30 +10,25 @@ install_vitasdk () {
...
-      tar xf "vitasdk-nightly.tar.bz2" -C $INSTALLDIR --strip-components=1
-      rm -f "vitasdk-nightly.tar.bz2"
+      wget -O- "$(get_download_link master osx)" | tar xj -C $INSTALLDIR --strip-components=1
      ;;
 
      Linux*)
       if [ -n "${TRAVIS}" ]; then
           sudo apt-get install libc6-i386 lib32stdc++6 lib32gcc1 patch
       fi
+      command -v curl || echo "curl missing (install using: apt install curl)"
```
Comment (d3m3vilurr) [inline include/install-vitasdk.sh]: it seems no more need curl, isn't it?

Comment (yne) [reply include/install-vitasdk.sh]: https://github.com/vitasdk/vdpm/blob/1d8138cf27aa4862919ea071a333ac922718ddc2/vdpm#L21
Not sure if it's still used.
If you confirm, I'll remove the line.

Comment (d3m3vilurr) [reply include/install-vitasdk.sh]: huh.... i got it...
how about just exit with message before installing?
if we always need the `curl`, it would be acceptable.

Comment (yne) [reply include/install-vitasdk.sh]: @d3m3vilurr sure, no problem.
I've updated my commit with your solution

File: include/install-vitasdk.sh [hunk 2]
```diff
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 get_download_link () {
-  curl -sL https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | python - $@
+  wget -qO- https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py | python - $@
```
Comment (d3m3vilurr) [inline include/install-vitasdk.sh:4]: now we don't need this change. isn't it?

Comment (yne) [reply include/install-vitasdk.sh:4]: yes
However, It might be a good start to get ride of curl completly and use the same binary everywere (good to know: wget is natively available even in alpine container)
